name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Smoke test
        run: ./do/do.sh -smoke

      - name: Staticcheck
        run: |
          # need to disable because staticcheck doesn't work on go 1.16
          # and GitHub Actions still has 1.16
          # go install honnef.co/go/tools/cmd/staticcheck@latest
          # staticcheck ./... || true
